export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

export const UPDATE_CART = "UPDATE_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_CART = "REMOVE_CART";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";

export const SHOW_CART_ITEMS = "SHOW_CART_ITEMS";
export const SHOW_CART_ITEMS_REQUEST = "SHOW_CART_ITEMS_REQUEST";
export const SHOW_CART_ITEMS_FAIL = "SHOW_CART_ITEMS_FAIL";

