export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

export const FETCH_A_PRODUCT_REQUEST = "FETCH_A_PRODUCT_REQUEST";
export const FETCH_A_PRODUCT_SUCCESS = "FETCH_A_PRODUCT_SUCCESS";
export const FETCH_A_PRODUCT_FAIL = "FETCH_A_PRODUCT_FAIL";

export const UPDATE_A_PRODUCT_REQUEST = "UPDATE_A_PRODUCT_REQUEST";
export const UPDATE_A_PRODUCT_SUCCESS = "UPDATE_A_PRODUCT_SUCCESS";
export const UPDATE_A_PRODUCT_FAIL = "UPDATE_A_PRODUCT_FAIL";

export const DELETE_A_PRODUCT_REQUEST = "DELETE_A_PRODUCT_REQUEST";
export const DELETE_A_PRODUCT_SUCCESS = "DELETE_A_PRODUCT_SUCCESS";
export const DELETE_A_PRODUCT_FAIL = "DELETE_A_PRODUCT_FAIL";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const GET_PRODUCT_REVIEWS_REQUEST = "GET_PRODUCT_REVIEWS_REQUEST";
export const GET_PRODUCT_REVIEWS_SUCCESS = "GET_PRODUCT_REVIEWS_SUCCESS";
export const GET_PRODUCT_REVIEWS_FAIL = "GET_PRODUCT_REVIEWS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

